"""Add openalex_enriched to publications

Revision ID: 20260224_0018
Revises: fa0c5e3262d5
Create Date: 2026-02-24 19:10:00.000000

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260224_0018'
down_revision: str | Sequence[str] | None = 'fa0c5e3262d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('openalex_enriched', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'openalex_enriched')
    # ### end Alembic commands ###
